// opencascade.cpp — entry point for the OpenCASCADE CxxWrap module.
// Each register_* function is defined in its own translation unit.
#include <jlcxx/jlcxx.hpp>

void register_occ_toptools_list(jlcxx::Module&);
void register_occ_gp(jlcxx::Module&);
void register_occ_topology(jlcxx::Module&);
void register_occ_geom(jlcxx::Module&);
void register_occ_builders(jlcxx::Module&);
void register_occ_io(jlcxx::Module&);
void register_occ_props(jlcxx::Module&);
void register_occ_fillet(jlcxx::Module&);
void register_occ_topo2(jlcxx::Module&);
void register_occ_adaptor(jlcxx::Module&);
void register_occ_analysis(jlcxx::Module&);
void register_occ_sweep(jlcxx::Module&);
void register_occ_wire(jlcxx::Module&);
void register_occ_sewing(jlcxx::Module&);
void register_occ_extrema(jlcxx::Module&);
void register_occ_builder2(jlcxx::Module&);
void register_occ_intersect(jlcxx::Module&);
void register_occ_shape_analysis(jlcxx::Module&);
void register_occ_breptools(jlcxx::Module&);
void register_occ_mesh(jlcxx::Module&);
void register_occ_shapefix2(jlcxx::Module&);
void register_occ_shapeupgrade(jlcxx::Module&);
void register_occ_feat(jlcxx::Module&);
void register_occ_thicksolid(jlcxx::Module&);
void register_occ_draft(jlcxx::Module&);
void register_occ_geom2d(jlcxx::Module&);
void register_occ_advanced(jlcxx::Module&);
void register_occ_xcaf(jlcxx::Module&);
void register_occ_breplib(jlcxx::Module&);
void register_occ_history(jlcxx::Module&);
void register_occ_bopalgo_analyzer(jlcxx::Module&);
void register_occ_bopalgo_builder(jlcxx::Module&);
void register_occ_feat_hole(jlcxx::Module&);
void register_occ_helix(jlcxx::Module&);
void register_occ_geom2d_int(jlcxx::Module&);
void register_occ_xcaf_material(jlcxx::Module&);
void register_occ_igescaf(jlcxx::Module&);
void register_occ_localanalysis(jlcxx::Module&);
void register_occ_gce(jlcxx::Module&);
void register_occ_units(jlcxx::Module&);
void register_occ_rwstl(jlcxx::Module&);
void register_occ_triangulation(jlcxx::Module&);
void register_occ_interface_static(jlcxx::Module&);
void register_occ_gltf(jlcxx::Module&);
void register_occ_fill(jlcxx::Module&);
void register_occ_hlr(jlcxx::Module&);
void register_occ_geomfill(jlcxx::Module&);
void register_occ_robj(jlcxx::Module&);
void register_occ_normalproj(jlcxx::Module&);
void register_occ_chfi2d(jlcxx::Module&);
void register_occ_geomplate(jlcxx::Module&);
void register_occ_geomconvert(jlcxx::Module&);
void register_occ_vrml(jlcxx::Module&);
void register_occ_findplane(jlcxx::Module&);
void register_occ_bintools(jlcxx::Module&);
void register_occ_shapecustom(jlcxx::Module&);

JLCXX_MODULE define_julia_module(jlcxx::Module& mod)
{
  register_occ_gp(mod);
  register_occ_topology(mod);
  register_occ_toptools_list(mod);
  register_occ_geom(mod);
  register_occ_geom2d(mod);
  register_occ_builders(mod);
  register_occ_io(mod);
  register_occ_props(mod);
  register_occ_fillet(mod);
  register_occ_topo2(mod);
  register_occ_adaptor(mod);
  register_occ_analysis(mod);
  register_occ_sweep(mod);
  register_occ_wire(mod);
  register_occ_sewing(mod);
  register_occ_extrema(mod);
  register_occ_builder2(mod);
  register_occ_intersect(mod);
  register_occ_shape_analysis(mod);
  register_occ_breptools(mod);
  register_occ_mesh(mod);
  register_occ_shapefix2(mod);
  register_occ_shapeupgrade(mod);
  register_occ_feat(mod);
  register_occ_thicksolid(mod);
  register_occ_draft(mod);
  register_occ_breplib(mod);
  register_occ_advanced(mod);
  // triangulation add_type's TopLoc_Location, now referenced by
  // occ_xcaf.cpp's assembly-component-tree bindings -- must precede it.
  register_occ_triangulation(mod);
  register_occ_xcaf(mod);
  register_occ_history(mod);
  register_occ_bopalgo_analyzer(mod);
  register_occ_bopalgo_builder(mod);
  register_occ_feat_hole(mod);
  register_occ_helix(mod);
  register_occ_geom2d_int(mod);
  register_occ_xcaf_material(mod);
  register_occ_igescaf(mod);
  register_occ_localanalysis(mod);
  register_occ_gce(mod);
  register_occ_units(mod);
  register_occ_rwstl(mod);
  register_occ_interface_static(mod);
  register_occ_gltf(mod);
  register_occ_fill(mod);
  register_occ_hlr(mod);
  register_occ_geomfill(mod);
  register_occ_robj(mod);
  register_occ_normalproj(mod);
  register_occ_chfi2d(mod);
  register_occ_geomplate(mod);
  register_occ_geomconvert(mod);
  register_occ_vrml(mod);
  register_occ_findplane(mod);
  register_occ_bintools(mod);
  register_occ_shapecustom(mod);
}
